#!/usr/bin/env python3
"""Convert ABBYY Lingvo DSL dictionary to MDict MDX format.

Fixes four DSL→MDX conversion issues:
  1. Duplicate headwords: DSL allows same headword with different
     translations; MDX doesn't. Merged with GROUP_CONCAT.
  2. Headword not in body: DSL readers display headword automatically;
     MDX doesn't. Prepended.
  3. Broken cross-refs: bword:// protocol fails with non-ASCII targets
     (punycode). Replaced with entry:// + URL-encoding.
  4. Sorted ordering: DSL entries are sorted; SQLite preserves order
     via ROWID.

Dependencies:
  pip install pyglossary mdict-utils

Usage:
  python scripts/dsl2mdx.py wikipedia-titlepair-en-zh-20260603.dsl
  # Output: wikipedia-titlepair-en-zh-20260603.mdx
"""

import argparse
import re
import sqlite3
import subprocess
import sys
import tempfile
import urllib.parse
from pathlib import Path


def dsl_to_sqlite(dsl_path: Path, db_path: Path) -> None:
    """Convert DSL to SQLite via pyglossary."""
    print(f"[1/4] DSL → SQLite ({dsl_path.name})")
    
    # Decompress if .dz
    if dsl_path.suffix == '.dz':
        import shutil
        if shutil.which('dictzip'):
            subprocess.run(['dictzip', '-d', str(dsl_path)], check=True)
            dsl_path = dsl_path.with_suffix('')
    
    subprocess.run([
        'pyglossary', str(dsl_path), str(db_path),
        '--read-format=ABBYYLingvoDSL',
        '--write-format=AyanDictSQLite',
        '--sqlite',
    ], check=True)
    print(f"  → {db_path}")


def fix_sqlite(db_path: Path) -> tuple[int, int]:
    """Fix conversion issues in-place. Returns (before_count, after_count)."""
    print("[2/4] Fixing duplicates, links, headwords")
    db = sqlite3.connect(str(db_path))
    
    before = db.execute('SELECT COUNT(*) FROM entry').fetchone()[0]
    
    # --- Fix 1: Merge duplicate headwords ---
    db.execute('''
        CREATE TABLE entry_merged AS
        SELECT term, GROUP_CONCAT(article, '\n') AS article
        FROM entry
        GROUP BY term
    ''')
    after = db.execute('SELECT COUNT(*) FROM entry_merged').fetchone()[0]
    db.execute('DROP TABLE entry')
    db.execute('ALTER TABLE entry_merged RENAME TO entry')
    print(f"  Merged {before} → {after} entries ({before - after} duplicates)")
    
    # --- Fix 2 + 3: bword:// → entry:// with URL encoding ---
    def encode_non_ascii_link(m):
        target = m.group(1)
        if any(ord(c) > 127 for c in target):
            encoded = urllib.parse.quote(target, safe='')
            return f'entry://{encoded}'
        return f'entry://{target}'
    
    def fix_links(article: str) -> str:
        article = article.replace('bword://', 'entry://')
        # SQLite REPLACE already handled bword→entry, now URL-encode non-ASCII
        return re.sub(
            r'entry://([^"]*)',
            encode_non_ascii_link,
            article,
        )
    
    db.create_function("fix_links", 1, fix_links)
    db.execute("UPDATE entry SET article = fix_links(article)")
    
    # --- Fix 4: Prepend headword to body ---
    db.execute("UPDATE entry SET article = term || '\n<br>\n' || article")
    
    db.commit()
    db.close()
    return before, after


def sqlite_to_mdx(db_path: Path, mdx_path: Path, title: str) -> None:
    """Convert fixed SQLite to MDX via mdict-utils."""
    print("[3/4] SQLite → MDX")
    
    # Create mdx table that mdict-utils expects
    db = sqlite3.connect(str(db_path))
    db.execute('DROP TABLE IF EXISTS mdx')
    db.execute('CREATE TABLE mdx AS SELECT term AS entry, article AS paraphrase FROM entry')
    db.commit()
    db.close()
    
    # mdict-utils: db → txt → mdx
    subprocess.run(['mdict', '--db-txt', str(db_path)], check=True)
    
    txt_path = Path(str(db_path) + '.txt')
    
    # Create title/description HTML files
    title_path = db_path.with_name('_title.html')
    desc_path = db_path.with_name('_description.html')
    title_path.write_text(title, encoding='utf-8')
    desc_path.write_text(
        f'Bidirectional Wikipedia title pairs from Wikidata. Generated by wikititlepair.',
        encoding='utf-8',
    )
    
    subprocess.run([
        'mdict',
        '--title', str(title_path),
        '--description', str(desc_path),
        '-a', str(txt_path),
        str(mdx_path),
    ], check=True)
    
    # Cleanup intermediates
    for p in [txt_path, title_path, desc_path]:
        p.unlink(missing_ok=True)
    
    print(f"  → {mdx_path} ({mdx_path.stat().st_size / 1e6:.1f} MB)")


def main():
    parser = argparse.ArgumentParser(
        description='Convert DSL dictionary to MDict MDX format',
    )
    parser.add_argument('dsl', type=Path, help='Input .dsl or .dsl.dz file')
    parser.add_argument('-o', '--output', type=Path, help='Output .mdx path (default: same name)')
    parser.add_argument('-t', '--title', default='Wikipedia Title Pairs',
                        help='Dictionary title shown in reader')
    parser.add_argument('--keep-db', action='store_true',
                        help='Keep intermediate SQLite database')
    args = parser.parse_args()
    
    dsl_path = args.dsl.resolve()
    if not dsl_path.exists():
        sys.exit(f"Error: {dsl_path} not found")
    
    mdx_path = args.output or dsl_path.with_suffix('.mdx')
    db_path = mdx_path.with_suffix('.db')
    
    print(f"DSL → MDX: {dsl_path.name} → {mdx_path.name}\n")
    
    dsl_to_sqlite(dsl_path, db_path)
    before, after = fix_sqlite(db_path)
    sqlite_to_mdx(db_path, mdx_path, args.title)
    
    if not args.keep_db:
        db_path.unlink()
        print(f"[4/4] Cleaned up {db_path.name}")
    
    print(f"\nDone. {after} entries in {mdx_path}")


if __name__ == '__main__':
    main()
